# Generated by Django 5.1.8 on 2026-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_fee_gate_and_mark_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardsetting',
            name='template',
            field=models.CharField(choices=[('cbse', 'CBSE style'), ('icse', 'ICSE style'), ('cambridge', 'Cambridge style'), ('ib', 'IB style'), ('ssc', 'SSC style'), ('other', 'Other style')], default='cbse', max_length=20),
        ),
    ]
