# Generated by Django 6.0.4 on 2026-09-23 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_backfill_default_complaint_master_data'),
        ('tenancy', '0023_backfill_missing_schooltenant_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('WhatsApp + Email', 'WhatsApp + Email'), ('SMS', 'SMS')], default='WhatsApp', max_length=32)),
                ('audience', models.CharField(default='All active inquiries', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('sent', 'Sent')], default='draft', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('replies', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_campaigns', to='tenancy.school')),
            ],
            options={
                'db_table': 'admission_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
